### PR TITLE
Metrics and model improvements

### PR DESCRIPTION
**Pull request by nbayt**
- Changed the kernel size on the initial layer to 5x5, seems to perform better overall.
 - Added metric printout and a rather crude confusion matrix.
 - Cleaned up and corrected the test case code (the single image we picked for examination.
   - Also draws the image now.

TODO (for me)
 - Still fill out interpretations of data for my part.
   - Usability
   - Limitations of our limited data pre-processing

### CODE REVIEW

**Comment by Sup3000gt** [comment]
sure

**Comment by nbayt** [comment]
Mixed the merge issues, please review and pull if good!

**Comment by Sup3000gt** [comment]
all good

**Comment by shomoitamitin** [comment]
Please merge the changes I have pulled! Thanks.

**Comment by shomoitamitin** [comment]
*I have pulled some comments to add my name on the contributor list, please
merge the request. *

**Comment by Sup3000gt** [comment]
it shows Merged

**Comment by Sup3000gt** [comment]
Do you see the changed?

**Comment by shomoitamitin** [comment]
No. Not my changes.


Shomoita Jahid Mitin
Assistant Professor,
Department of Computer Science and Engineering
Asian University of Bangladesh

**Comment by Sup3000gt** [comment]
it is wired

**Comment by Sup3000gt** [comment]
don't worry, just get it done. we will figure out the merged part in class on wednesday

**Comment by shomoitamitin** [comment]
Okay. Thanks.


Shomoita Jahid Mitin
Assistant Professor,
Department of Computer Science and Engineering
Asian University of Bangladesh

**Comment by shomoitamitin** [comment]
Please give me push access on github so that I can upload this image.


Shomoita Jahid Mitin
Assistant Professor,
Department of Computer Science and Engineering
Asian University of Bangladesh

**Comment by Sup3000gt** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:SimSun;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:DengXian;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:DengXian;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:SimSun;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	text-align:justify;
	text-justify:inter-ideograph;
	font-size:10.5pt;
	font-family:DengXian;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
/* Page Definitions */
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 90.0pt 72.0pt 90.0pt;}
div.WordSection1
	{page:WordSection1;}

**Pull request merged**
